### ISSUE TITLE
Unable to render result

### ISSUE THREAD

**Issue by abuecker** [mkocabas/VIBE#35] opened 2020-03-09 01:11 UTC
Thanks for the great work.  I'm running the solve in a Docker container using the CPU for calculations and Mesa offscreen software rendering for `pyrender`.  Unfortunately, I get the following error message while rendering at this line:

https://github.com/mkocabas/VIBE/blob/master/lib/utils/renderer.py#L120

```
  File "/opt/vibe/lib/utils/renderer.py", line 120, in render
    output_img = rgb[:, :, :-1] * valid_mask + (1 - valid_mask) * img
ValueError: operands could not be broadcast together with shapes (1080,1920,2) (1080,1920,3)
```

Any help getting past this point would be much appreciated.

**Comment by ikvision** [comment] 2020-03-09 04:19
Looks like in this sum one image includes only two channels while the other has all three (RBG) channels
To add a dummy channel you can use:
```python
zeros_channel = np.zeros((img.shape[0], img.shape[1]),dtype=uint)
c1,c2 = cv2.split(img)
merged_img = cv2.merge((c1,c2,zeros_channel))
```
But the best approach would be to find the root cause for the missing channel

**Comment by mkocabas** [comment] 2020-03-09 09:30
Hi @abuecker,

I tried rendering with Mesa and everything seems to work fine. Btw, I followed this to install Mesa: https://colab.research.google.com/drive/1Z71mHIc-Sqval92nK290vAsHZRUkCjUx

Could you give it a try?

**Comment by mkocabas** [comment] 2020-03-09 18:39
Closing it now, feel free to reopen if you need.

**Closed by mkocabas** 2020-03-09 18:39 UTC

**Comment by abuecker** [comment] 2020-03-10 01:25
I tried using the Mesa debian package file from your collab notebook but had no luck.  It is still expecting a GL context.

I was able to get the suggested building Mesa from source described in the Pyrender docs [here](https://pyrender.readthedocs.io/en/latest/install/index.html) to not complain about GL errors, but then it barks about the missing channel when merging everything together.

I haven't been able to get @ikvision suggestion to work yet.  Getting an error unpacking channels in the `split` operation.

Here is the [Dockerfile](https://gist.github.com/abuecker/c47c7899085803bfc93b162ecdfdb64a) I'm using.

**Comment by Xianjin111** [comment] 2020-07-31 02:56
> Thanks for the great work. I'm running the solve in a Docker container using the CPU for calculations and Mesa offscreen software rendering for `pyrender`. Unfortunately, I get the following error message while rendering at this line:
> 
> https://github.com/mkocabas/VIBE/blob/master/lib/utils/renderer.py#L120
> 
> ```
>   File "/opt/vibe/lib/utils/renderer.py", line 120, in render
>     output_img = rgb[:, :, :-1] * valid_mask + (1 - valid_mask) * img
> ValueError: operands could not be broadcast together with shapes (1080,1920,2) (1080,1920,3)
> ```
> 
> Any help getting past this point would be much appreciated.

I also encountered this problem, would you like to ask whether it has been solved in the end. Thanks a lot.

**Comment by AngioC** [comment] 2020-10-15 10:03
Any news about to solve this error?

**Comment by ljq2020** [comment] 2021-03-28 15:00
You can change `output_img = rgb[:, :, :-1] * valid_mask + (1 - valid_mask) * img`(in `renderer.py`) into `output_img = rgb[:, :, :] * valid_mask + (1 - valid_mask) * img`
