### ISSUE TITLE
About the weakPerspectiveCamera

### ISSUE THREAD

**Issue by quyanqiu** [mkocabas/VIBE#85] opened 2020-05-27 03:04 UTC
How do you construct the 4*4 projection matrix below?
![image](https://user-images.githubusercontent.com/11349003/82973316-9e58f000-a009-11ea-9b56-688eea5d0b1a.png)
Any reference?
thx!

**Comment by ikvision** [comment] 2020-05-27 03:18
VIBE predicts pred_camera = (scale,translation_x, tranlsation_y)
This readme may help you: [weak perspective camera ](https://github.com/ikvision/ikvision.github.io/blob/master/README.md#5-predicted-camera-parameters)

**Comment by quyanqiu** [comment] 2020-05-27 03:25
@ikvision thx,actually I know what is weakperspectivecamera,I just curious about how to build this 4*4 matrix,it seems that this matrix just like the openGL projection matrix,But I dont know how to build that

**Comment by ikvision** [comment] 2020-05-27 04:11
In the code you attached the 

> How do you construct the 4*4 projection matrix below?
> ![image](https://user-images.githubusercontent.com/11349003/82973316-9e58f000-a009-11ea-9b56-688eea5d0b1a.png)
> Any reference?
> thx!

I find it difficult to understand `get_projection_matrix` function as its inputs `width` and `height` are in use.
The function requires scale_x,scale_y,translation_x,translation_y included in pred_cam (assuming scale_x=scale_y)
OpenGL Projection Matrix, I guess you refer to perspective project (Orthographic project is less common), this code implements it weak perspective to perspective conversion:
https://github.com/mkocabas/VIBE/blob/945fd109eaace037b38c56e22ec235a9d3c5100a/lib/models/spin.py#L432-L436

**Comment by athn-nik** [comment] 2020-06-24 12:26
Seems like the issue is resolved. I am closing it for now.

**Closed by athn-nik** 2020-06-24 12:26 UTC

**Comment by nnop** [comment] 2022-11-06 13:46
`scale` is object frame to normalized device coordinate(with data in range [-1, 1]), 
`(tx, ty)` is in camera frame(or view frame) whose unit is meter, 
right? @ikvision

**Comment by lvZic** [comment] 2022-11-11 03:24
> `scale` is object frame to normalized device coordinate(with data in range [-1, 1]), `(tx, ty)` is in camera frame(or view frame) whose unit is meter, right? @ikvision

I think scale is focal length / trans_z, and the (tx, ty) has the same unit with annotation xyz.
